forge "http://forge.puppetlabs.com"

mod "apt",
    :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod "php",
    :git => "git://github.com/saz/puppet-php.git"

mod "nginx",
    :git => "git://github.com/davidwinter/puppet-nginx.git"

mod "nodejs",
    :git => "git://github.com/puppetlabs/puppetlabs-nodejs.git"

mod "rsyslog",
    :git => "git://github.com/saz/puppet-rsyslog.git"

mod "mysql",
    :git => "git://github.com/puppetlabs/puppetlabs-mysql.git"

mod "vcsrepo",
    :git => "git://github.com/puppetlabs/puppetlabs-vcsrepo.git"
