forge "http://forge.puppetlabs.com"

mod "apt",
    :git => "git://github.com/puppetlabs/puppetlabs-apt.git"

mod "ruby",
    :git => "git://github.com/puppetlabs/puppetlabs-ruby.git"

mod "java",
    :git => "git://github.com/puppetlabs/puppetlabs-java.git"

mod "php",
    :git => "git://github.com/example42/puppet-php.git"

mod "phpfpm",
    :git => "git://github.com/Slashbunny/puppet-phpfpm.git"

mod "elasticsearch",
    :git => "git://github.com/elasticsearch/puppet-elasticsearch.git"

mod "nginx",
    :git => "git://github.com/davidwinter/puppet-nginx.git"

mod "nodejs",
    :git => "git://github.com/puppetlabs/puppetlabs-nodejs.git"

mod "mailcatcher",
    :git => "git://github.com/actionjack/puppet-mailcatcher.git"

mod "rsyslog",
    :git => "git://github.com/saz/puppet-rsyslog.git"

mod "redis",
    :git => "git://github.com/tristankenney/puppet-redis.git"

mod "mysql",
    :git => "git://github.com/puppetlabs/puppetlabs-mysql.git"

mod "vcsrepo",
    :git => "git://github.com/puppetlabs/puppetlabs-vcsrepo.git"
